apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ago-chat

resources:
  - namespace.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - redis.yaml
  - minio.yaml
  - api.yaml
  - worker.yaml
  - webhooks.yaml
